spring:
  application:
    name: sb-server
  datasource:
    url: jdbc:postgresql://172.25.235.177:5432/item
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: false
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect

